import { getDb } from "../api/queries/connection";
import { products } from "./schema";

const sampleProducts = [
  {
    name: "Street Graffiti Hoodie",
    category: "hoodie" as const,
    description: "Bold graffiti street art design hoodie with urban style",
    price: "24.99",
    colors: JSON.stringify(["#1F2937", "#FFFFFF", "#6D4AFF", "#DC2626"]),
    sizes: JSON.stringify(["S", "M", "L", "XL"]),
    rating: "4.8",
    reviewCount: 128,
    image: "/products/product-1.png",
    creatorName: "Urban Creator",
    isNew: true,
  },
  {
    name: "Skull Floral Tee",
    category: "t-shirt" as const,
    description: "Dark gothic skull surrounded by purple roses",
    price: "19.99",
    colors: JSON.stringify(["#000000", "#374151", "#1F2937"]),
    sizes: JSON.stringify(["S", "M", "L", "XL", "XXL"]),
    rating: "4.7",
    reviewCount: 89,
    image: "/products/product-2.png",
    creatorName: "Dark Vision",
    isNew: false,
  },
  {
    name: "Sunset Vibes Sweater",
    category: "sweater" as const,
    description: "Retro sunset with palm trees silhouette design",
    price: "29.99",
    colors: JSON.stringify(["#F5F5DC", "#FFFFFF", "#1F2937"]),
    sizes: JSON.stringify(["S", "M", "L", "XL"]),
    rating: "4.9",
    reviewCount: 156,
    image: "/products/product-3.png",
    creatorName: "Creative Soul",
    isNew: false,
  },
  {
    name: "Neon Space Tank",
    category: "tank-top" as const,
    description: "Neon galaxy space astronaut design tank top",
    price: "16.99",
    colors: JSON.stringify(["#000000", "#1F2937"]),
    sizes: JSON.stringify(["S", "M", "L", "XL"]),
    rating: "4.6",
    reviewCount: 67,
    image: "/products/product-4.png",
    creatorName: "Neon Art",
    isNew: false,
  },
  {
    name: "Never Stop Dreaming Hoodie",
    category: "hoodie" as const,
    description: "Motivational typography design on olive green",
    price: "27.99",
    colors: JSON.stringify(["#556B2F", "#1F2937", "#374151"]),
    sizes: JSON.stringify(["S", "M", "L", "XL", "XXL"]),
    rating: "4.8",
    reviewCount: 203,
    image: "/products/product-5.png",
    creatorName: "Motivasi Store",
    isNew: false,
  },
  {
    name: "Minimalist Line Art Tee",
    category: "t-shirt" as const,
    description: "Clean geometric mountain landscape line art",
    price: "17.99",
    colors: JSON.stringify(["#FFFFFF", "#F9FAFB", "#1F2937"]),
    sizes: JSON.stringify(["S", "M", "L", "XL"]),
    rating: "4.5",
    reviewCount: 92,
    image: "/products/product-6.png",
    creatorName: "Minimal Studio",
    isNew: false,
  },
  {
    name: "Cyberpunk Jacket",
    category: "jacket" as const,
    description: "Futuristic cyberpunk circuit board pattern leather jacket",
    price: "39.99",
    colors: JSON.stringify(["#000000", "#1F2937"]),
    sizes: JSON.stringify(["M", "L", "XL", "XXL"]),
    rating: "4.9",
    reviewCount: 134,
    image: "/products/product-7.png",
    creatorName: "Future Wear",
    isNew: true,
  },
  {
    name: "Japanese Wave Tee",
    category: "t-shirt" as const,
    description: "Traditional Japanese Great Wave art design",
    price: "18.99",
    colors: JSON.stringify(["#FFFFFF", "#F5F5DC"]),
    sizes: JSON.stringify(["S", "M", "L", "XL", "XXL"]),
    rating: "4.8",
    reviewCount: 111,
    image: "/products/product-9.png",
    creatorName: "Asian Culture",
    isNew: false,
  },
  {
    name: "Galaxy Hoodie",
    category: "hoodie" as const,
    description: "Stunning cosmic galaxy nebula pattern hoodie",
    price: "26.99",
    colors: JSON.stringify(["#000000", "#1F2937", "#374151"]),
    sizes: JSON.stringify(["S", "M", "L", "XL"]),
    rating: "4.6",
    reviewCount: 95,
    image: "/products/product-10.png",
    creatorName: "Space Creator",
    isNew: false,
  },
  {
    name: "Butterfly Dream Sweater",
    category: "sweater" as const,
    description: "Watercolor butterfly dream design sweater",
    price: "28.99",
    colors: JSON.stringify(["#FFFFFF", "#F5F5DC", "#FFF0F5"]),
    sizes: JSON.stringify(["S", "M", "L", "XL"]),
    rating: "4.8",
    reviewCount: 142,
    image: "/products/product-11.png",
    creatorName: "Dreamy Design",
    isNew: false,
  },
  {
    name: "Urban Backpack 3D",
    category: "asset-3d" as const,
    description: "Modern urban backpack with geometric patterns",
    price: "22.99",
    colors: JSON.stringify(["#6B7280", "#374151", "#000000"]),
    sizes: JSON.stringify(["One Size"]),
    rating: "4.9",
    reviewCount: 66,
    image: "/products/product-12.png",
    creatorName: "3D Gear",
    isNew: false,
  },
];

async function seed() {
  const db = getDb();

  console.log("Seeding products...");

  for (const product of sampleProducts) {
    await db.insert(products).values({
      ...product,
      colors: product.colors as unknown as string[],
      sizes: product.sizes as unknown as string[],
    });
  }

  console.log(`Seeded ${sampleProducts.length} products.`);
}

seed().catch(console.error);
